default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: '161int'
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: seta-rails-api-dev

test:
  <<: *default
  database: seta-rails-api-test

production:
  <<: *default
  database: seta-rails-api-prod
